package com.bonitasoft.connectors.gdrive;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Objects;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;
import java.util.zip.ZipOutputStream;

/**
 * Patches a Bonita .bar file for testing purposes.
 *
 * <p>A .bar file is a ZIP archive generated by Bonita Studio (Deploy button) containing:</p>
 * <pre>
 *   process-design.xml          -- compiled process definition (NOT the .proc XMI)
 *   actorMapping.xml            -- actor-to-group mapping
 *   form-mapping.xml            -- form mappings (empty for automation processes)
 *   parameters.properties       -- process parameters
 *   resources/process.bpmn      -- BPMN representation
 *   connector/*.impl            -- connector implementation descriptors
 *   classpath/*.jar             -- connector JARs and dependencies
 * </pre>
 *
 * <p>The {@code process-design.xml} is a compiled format that only Bonita Studio can produce
 * from a {@code .proc} XMI file. Therefore, the .bar must be generated ONCE from Studio
 * and placed in {@code src/test/resources/processes/}. This utility patches it for
 * different test environments (e.g., changing the Service Account JSON path).</p>
 *
 * <h3>Usage in tests:</h3>
 * <pre>{@code
 * Path sourceBar = Path.of("src/test/resources/processes/GDrive_Connector_Test--1.0.bar");
 * Path patched = BarPatcher.builder(sourceBar)
 *         .serviceAccountJsonPath("/path/to/sa.json")
 *         .processVersion("1.0-test")
 *         .build();
 *
 * // Deploy patched .bar to Bonita Runtime via REST API...
 * }</pre>
 *
 * <h3>How to generate the source .bar (one-time):</h3>
 * <ol>
 *   <li>Open {@code GDriveConnectorTestProcess-1.0.proc} in Bonita Studio</li>
 *   <li>Import the connector: Extensions &rarr; Import &rarr; select {@code -bonita.jar}</li>
 *   <li>Configure process variables ({@code serviceAccountJsonPath}, {@code gdriveFolderId})</li>
 *   <li>Click Deploy &rarr; save the .bar to {@code src/test/resources/processes/}</li>
 * </ol>
 */
public final class BarPatcher {

    /** Connector impl file names to inject from the fat JAR into the .bar connector/ directory. */
    private static final String[] CONNECTOR_IMPLS = {
            "gdrive-search.impl", "gdrive-create-folder.impl", "gdrive-upload.impl",
            "gdrive-download.impl", "gdrive-copy.impl", "gdrive-move.impl",
            "gdrive-export.impl", "gdrive-delete.impl"
    };

    private BarPatcher() {
        // Utility class
    }

    /**
     * Creates a new builder for patching a .bar file.
     *
     * @param sourceBar path to the Studio-generated .bar file
     * @return a new builder instance
     * @throws NullPointerException if sourceBar is null
     */
    public static Builder builder(Path sourceBar) {
        return new Builder(Objects.requireNonNull(sourceBar, "sourceBar must not be null"));
    }

    /**
     * Convenience method: patches only the Service Account JSON path.
     *
     * @param sourceBar  path to the Studio-generated .bar file
     * @param saJsonPath absolute path to the Service Account JSON file
     * @return path to the patched .bar (temporary file, deleted on JVM exit)
     * @throws IOException if reading/writing the .bar fails
     */
    public static Path patchServiceAccountPath(Path sourceBar, String saJsonPath) throws IOException {
        return builder(sourceBar)
                .serviceAccountJsonPath(saJsonPath)
                .build();
    }

    /**
     * Builder for configuring and applying .bar patches.
     */
    public static final class Builder {

        private final Path sourceBar;
        private String saJsonPath;
        private String processVersion;
        private Path connectorJar;

        private Builder(Path sourceBar) {
            this.sourceBar = sourceBar;
        }

        /**
         * Sets the connector fat JAR to extract .impl files from.
         * These are injected into the .bar's connector/ directory so the Runtime
         * can resolve connector implementations without Studio Deploy.
         *
         * @param connectorJar path to the -bonita.jar (fat JAR with .impl files)
         * @return this builder
         */
        public Builder connectorJar(Path connectorJar) {
            this.connectorJar = connectorJar;
            return this;
        }

        /**
         * Sets the Service Account JSON file path.
         *
         * <p>This patches Groovy expressions in {@code process-design.xml} that read the SA key:
         * {@code new File(serviceAccountJsonPath).text} becomes
         * {@code new File("/absolute/path/to/sa.json").text}.</p>
         *
         * @param saJsonPath absolute path to the SA JSON file (forward slashes recommended)
         * @return this builder
         */
        public Builder serviceAccountJsonPath(String saJsonPath) {
            this.saJsonPath = saJsonPath;
            return this;
        }

        /**
         * Sets a new process version.
         *
         * <p>This patches the version attribute in {@code process-design.xml}, e.g.,
         * {@code version="1.0"} becomes {@code version="1.0-test"}.</p>
         *
         * @param version new process version string
         * @return this builder
         */
        public Builder processVersion(String version) {
            this.processVersion = version;
            return this;
        }

        /**
         * Applies all configured patches and produces the patched .bar file.
         *
         * <p>The returned file is a temporary file that will be deleted when the JVM exits.
         * The original .bar is never modified.</p>
         *
         * @return path to the patched .bar file
         * @throws IOException              if reading/writing fails
         * @throws IllegalArgumentException if sourceBar does not exist or is not a file
         */
        public Path build() throws IOException {
            if (!Files.isRegularFile(sourceBar)) {
                throw new IllegalArgumentException(
                        "Source .bar not found: " + sourceBar.toAbsolutePath()
                                + ". Generate it from Bonita Studio first (see BarPatcher javadoc).");
            }

            Path outputBar = Files.createTempFile("gdrive-test-", ".bar");
            outputBar.toFile().deleteOnExit();

            try (InputStream fis = Files.newInputStream(sourceBar);
                 ZipInputStream zis = new ZipInputStream(fis);
                 ZipOutputStream zos = new ZipOutputStream(Files.newOutputStream(outputBar))) {

                ZipEntry entry;
                while ((entry = zis.getNextEntry()) != null) {
                    byte[] content = readAllBytes(zis);

                    if ("process-design.xml".equals(entry.getName())) {
                        content = patchProcessDesign(content);
                    }

                    // Create a clean entry (no extra metadata from the original)
                    ZipEntry outEntry = new ZipEntry(entry.getName());
                    zos.putNextEntry(outEntry);
                    zos.write(content);
                    zos.closeEntry();
                }

                // Inject connector .impl files from the fat JAR (if not already present)
                if (connectorJar != null && Files.isRegularFile(connectorJar)) {
                    injectConnectorImpls(zos);
                }
            }

            return outputBar;
        }

        /**
         * Extracts .impl files from the connector fat JAR and injects them
         * into the .bar's connector/ directory. This is what Bonita Studio does
         * during Deploy — it reads the .impl from each connector JAR and places
         * them in the .bar so the Runtime can resolve implementations.
         */
        private void injectConnectorImpls(ZipOutputStream zos) throws IOException {
            try (InputStream jarIs = Files.newInputStream(connectorJar);
                 java.util.zip.ZipInputStream jarZis = new java.util.zip.ZipInputStream(jarIs)) {
                java.util.zip.ZipEntry jarEntry;
                while ((jarEntry = jarZis.getNextEntry()) != null) {
                    String name = jarEntry.getName();
                    if (name.endsWith(".impl")) {
                        byte[] implContent = readAllBytes(jarZis);
                        // Extract impl ID from content for the filename
                        // e.g., gdrive-search.impl → connector/gdrive-search-impl-1.0.0-SNAPSHOT.impl
                        String implId = extractImplId(implContent);
                        String barEntryName = "connector/" + implId + ".impl";
                        zos.putNextEntry(new ZipEntry(barEntryName));
                        zos.write(implContent);
                        zos.closeEntry();
                    }
                }
            }
        }

        /** Extracts implementationId + implementationVersion from .impl XML content. */
        private static String extractImplId(byte[] implContent) {
            String xml = new String(implContent, StandardCharsets.UTF_8);
            String id = extractXmlValue(xml, "implementationId");
            String version = extractXmlValue(xml, "implementationVersion");
            return (id != null && version != null) ? id + "-" + version : "unknown";
        }

        private static String extractXmlValue(String xml, String tag) {
            int start = xml.indexOf("<" + tag + ">");
            int end = xml.indexOf("</" + tag + ">");
            if (start >= 0 && end > start) {
                return xml.substring(start + tag.length() + 2, end);
            }
            return null;
        }

        /**
         * Patches the process-design.xml content with configured values.
         */
        private byte[] patchProcessDesign(byte[] original) {
            String xml = new String(original, StandardCharsets.UTF_8);

            if (saJsonPath != null) {
                // Normalize path separators to forward slashes for Groovy compatibility
                String normalizedPath = saJsonPath.replace("\\", "/");

                // Pattern 1: Groovy script reading SA from a variable
                // e.g., new File(serviceAccountJsonPath).text
                xml = xml.replace(
                        "new File(serviceAccountJsonPath).text",
                        "new File(\"" + normalizedPath + "\").text");

                // Pattern 2: Already-hardcoded path from a previous patch
                // e.g., new File("/old/path/sa.json").text
                xml = xml.replaceAll(
                        "new File\\(\"[^\"]+\"\\)\\.text",
                        "new File(\"" + normalizedPath + "\").text");
            }

            if (processVersion != null) {
                // Patch the process version attribute
                // Matches: name="GDrive Connector Test" version="1.0"
                xml = xml.replaceFirst(
                        "(name=\"GDrive Connector Test\"\\s+version=\")[^\"]+\"",
                        "$1" + processVersion + "\"");
            }

            return xml.getBytes(StandardCharsets.UTF_8);
        }
    }

    /**
     * Reads all remaining bytes from the current ZIP entry without closing the stream.
     *
     * <p>We cannot use {@code InputStream.readAllBytes()} directly on a ZipInputStream
     * in all JDK versions, so we use a manual buffer approach for reliability.</p>
     */
    private static byte[] readAllBytes(ZipInputStream zis) throws IOException {
        ByteArrayOutputStream baos = new ByteArrayOutputStream(8192);
        byte[] buffer = new byte[8192];
        int len;
        while ((len = zis.read(buffer)) != -1) {
            baos.write(buffer, 0, len);
        }
        return baos.toByteArray();
    }
}
